// Package generators contains code generators for Sleet CLI.
package generators

import (
	"fmt"
	"strings"

	"github.com/SleetCo/sleet-orm-cli/internal/loader"
)

// GenerateEmmyLua produces a ---@meta Lua file with:
//  1. XxxRecord  — row shape for SELECT results
//  2. XxxTable   — schema object type extending SleetTableDef<XxxRecord>
//                  with precise ColumnDef<T> fields
//  3. Sleet.table @overload — one overload per table so that
//                  sl.table('users', ...) is inferred as UsersTable by LuaLS,
//                  enabling the full zero-annotation type inference chain:
//                  sl.table → UsersTable → from() infers R → execute(): UsersRecord[]
//
// Core Sleet types (ColumnDef, SleetTableDef, SleetPreSelectBuilder, etc.)
// live in lib/annotations.lua.
func GenerateEmmyLua(tables []*loader.TableDef) string {
	var sb strings.Builder

	sb.WriteString("---@meta\n")
	sb.WriteString("-- AUTO-GENERATED by sleet-cli. DO NOT EDIT MANUALLY.\n")
	sb.WriteString("-- Regenerate with: sleet generate <your-schema.lua>\n")
	sb.WriteString("-- https://github.com/SleetCo/sleet-orm\n\n")

	// ── XxxRecord ──────────────────────────────────────────────────────
	sb.WriteString("-- ────────────────────────────────────────────────\n")
	sb.WriteString("-- Row shapes — returned by execute() with full type inference.\n")
	sb.WriteString("-- No manual ---@type needed: db.select().from(s.users).execute()\n")
	sb.WriteString("-- automatically resolves to UsersRecord[] via SleetTableDef<R>.\n")
	sb.WriteString("-- ────────────────────────────────────────────────\n\n")

	for _, tbl := range tables {
		pascal := toPascalCase(tbl.Name)
		sb.WriteString(fmt.Sprintf("---@class %sRecord\n", pascal))
		for _, col := range tbl.Columns {
			line := fmt.Sprintf("---@field %-24s %s", col.Name, luaTypeName(col))
			if col.Comment != "" {
				line += " " + col.Comment
			}
			sb.WriteString(line + "\n")
		}
		sb.WriteString("\n")
	}

	// ── XxxTable ───────────────────────────────────────────────────────
	sb.WriteString("-- ────────────────────────────────────────────────\n")
	sb.WriteString("-- Table objects — each extends SleetTableDef<XxxRecord> so that\n")
	sb.WriteString("-- the generic fun<R> in SleetPreSelectBuilder.from() can infer R.\n")
	sb.WriteString("-- ────────────────────────────────────────────────\n\n")

	for _, tbl := range tables {
		pascal := toPascalCase(tbl.Name)
		sb.WriteString(fmt.Sprintf("---@class %sTable: SleetTableDef<%sRecord>\n", pascal, pascal))
		for _, col := range tbl.Columns {
			line := fmt.Sprintf("---@field %-24s ColumnDef<%s>", col.Name, luaTypeName(col))
			if col.Comment != "" {
				line += " " + col.Comment
			}
			sb.WriteString(line + "\n")
		}
		sb.WriteString("\n")
	}

	// ── XxxSelectBuilder ──────────────────────────────────────────────
	// One concrete (non-generic) builder class per table.  Every chained method
	// returns the same XxxSelectBuilder so LuaLS never needs to propagate a
	// generic type parameter — it always works with concrete types.
	// execute() returns XxxRecord[] directly.
	//
	// The generic SleetSelectBuilder<T> approach was abandoned because LuaLS
	// cannot propagate @class generic parameters through @field fun() return
	// types in a method chain, causing T to be lost after the first call.
	sb.WriteString("-- ────────────────────────────────────────────────\n")
	sb.WriteString("-- Per-table select builders — concrete, no generics.\n")
	sb.WriteString("-- execute() returns the precise XxxRecord[] type.\n")
	sb.WriteString("-- ────────────────────────────────────────────────\n\n")

	for _, tbl := range tables {
		pascal := toPascalCase(tbl.Name)
		sb.WriteString(fmt.Sprintf("---@class %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field where     fun(cond: table): %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field limit     fun(n: integer): %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field offset    fun(n: integer): %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field orderBy   fun(col: ColumnDef, dir?: string): %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field groupBy   fun(col: ColumnDef): %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field leftJoin  fun(tbl: table, on: table): %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field innerJoin fun(tbl: table, on: table): %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field rightJoin fun(tbl: table, on: table): %sSelectBuilder\n", pascal))
		sb.WriteString(fmt.Sprintf("---@field execute   fun(): %sRecord[]\n", pascal))
		sb.WriteString("---@field toSQL     fun(): string, table\n")
		sb.WriteString("\n")
	}

	// ── SleetPreSelectBuilder.from overloads ───────────────────────────
	// 'from' is only declared here (not in annotations.lua).  A generic
	// 'fun(tbl: table)' fallback in annotations.lua would also match any
	// XxxTable argument (table is the supertype), causing LuaLS to union
	// the two return types (UsersSelectBuilder | SleetPreSelectBuilder) and
	// ultimately produce UsersRecord[]|table[] instead of UsersRecord[].
	// Keeping 'from' exclusively in types.lua avoids this union.
	sb.WriteString("-- ────────────────────────────────────────────────\n")
	sb.WriteString("-- SleetPreSelectBuilder.from overloads\n")
	sb.WriteString("-- db.select().from(s.users) → UsersSelectBuilder\n")
	sb.WriteString("-- ────────────────────────────────────────────────\n\n")

	sb.WriteString("---@class SleetPreSelectBuilder\n")
	for _, tbl := range tables {
		pascal := toPascalCase(tbl.Name)
		sb.WriteString(fmt.Sprintf("---@field from fun(tbl: %sTable): %sSelectBuilder\n", pascal, pascal))
	}
	sb.WriteString("\n")

	// ── Sleet.table @overload ──────────────────────────────────────────
	// One overload per table.  LuaLS resolves the most specific overload first,
	// so sl.table('users', {...}) returns UsersTable instead of the generic T.
	// The generic fallback (---@generic T: table … ---@return T) in
	// annotations.lua handles any table name not listed here.
	sb.WriteString("-- ────────────────────────────────────────────────\n")
	sb.WriteString("-- Sleet.table overloads — sl.table('users', ...) → UsersTable\n")
	sb.WriteString("-- These take priority over the generic fallback in annotations.lua.\n")
	sb.WriteString("-- ────────────────────────────────────────────────\n\n")

	for _, tbl := range tables {
		pascal := toPascalCase(tbl.Name)
		sb.WriteString(fmt.Sprintf("---@overload fun(name: '%s', columns: table): %sTable\n", tbl.Name, pascal))
	}
	sb.WriteString("---@diagnostic disable-next-line: inject-field\n")
	sb.WriteString("function Sleet.table(name, columns) end\n")

	return sb.String()
}

// luaTypeName maps a SQL column type to a Lua type annotation string.
func luaTypeName(col *loader.ColumnDef) string {
	switch strings.ToUpper(col.Type) {
	case "INT", "BIGINT", "SMALLINT", "TINYINT":
		return "integer"
	case "FLOAT", "DOUBLE", "DECIMAL":
		return "number"
	case "BOOLEAN":
		return "boolean"
	case "JSON":
		return "table"
	default:
		return "string"
	}
}

// toPascalCase converts snake_case or camelCase to PascalCase.
// "gang_members" → "GangMembers"
func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' })
	var sb strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return sb.String()
}

// toCamelCase converts snake_case to camelCase.
func toCamelCase(s string) string {
	p := toPascalCase(s)
	if len(p) == 0 {
		return s
	}
	return strings.ToLower(p[:1]) + p[1:]
}
