package generators

import (
	"fmt"
	"strings"

	"github.com/SleetCo/sleet-orm-cli/internal/loader"
)

// GenerateSchemaLua produces a schema.lua file from a slice of TableDefs.
// This is used by the `sleet pull` command to reverse-engineer a live database.
func GenerateSchemaLua(tables []*loader.TableDef) string {
	var sb strings.Builder

	sb.WriteString("-- AUTO-GENERATED by sleet-cli pull. Review before committing.\n")
	sb.WriteString("-- https://github.com/SleetCo/sleet-orm\n\n")
	sb.WriteString("local sl = Sleet\n\n")

	varNames := make([]string, 0, len(tables))

	for _, tbl := range tables {
		varName := toCamelCase(tbl.Name)
		varNames = append(varNames, varName)

		sb.WriteString(fmt.Sprintf("local %s = sl.table('%s', {\n", varName, tbl.Name))

		for _, col := range tbl.Columns {
			sb.WriteString(fmt.Sprintf("    %-20s = %s,\n", col.Name, colBuilderExpr(col)))
		}

		sb.WriteString("})\n\n")
	}

	sb.WriteString("return {\n")
	for i, varName := range varNames {
		tblName := tables[i].Name
		sb.WriteString(fmt.Sprintf("    %-20s = %s,\n", toCamelCase(tblName), varName))
	}
	sb.WriteString("}\n")

	return sb.String()
}

// colBuilderExpr generates a sl.xxx().chain()... expression for a column.
func colBuilderExpr(col *loader.ColumnDef) string {
	var parts []string

	// Base type
	t := strings.ToLower(col.Type)
	switch t {
	case "int":
		if col.AutoIncrement {
			parts = append(parts, "sl.serial()")
		} else {
			parts = append(parts, "sl.int()")
		}
	case "bigint":
		if col.AutoIncrement {
			parts = append(parts, "sl.bigserial()")
		} else {
			parts = append(parts, "sl.bigint()")
		}
	case "varchar", "char":
		l := col.Length
		if l <= 0 {
			l = 255
		}
		parts = append(parts, fmt.Sprintf("sl.%s(%d)", t, l))
	case "decimal":
		p, s := col.Precision, col.Scale
		if p <= 0 {
			p = 10
		}
		if s <= 0 {
			s = 2
		}
		parts = append(parts, fmt.Sprintf("sl.decimal(%d, %d)", p, s))
	case "tinyint", "boolean":
		parts = append(parts, "sl.boolean()")
	default:
		parts = append(parts, fmt.Sprintf("sl.%s()", t))
	}

	// Chain modifiers
	if col.PrimaryKey {
		parts = append(parts, "primaryKey()")
	} else {
		if col.NotNull {
			parts = append(parts, "notNull()")
		}
		if col.Unique {
			parts = append(parts, "unique()")
		}
	}

	if col.DefaultNow {
		parts = append(parts, "defaultNow()")
	} else if col.Default != nil {
		def := *col.Default
		switch strings.ToUpper(col.Type) {
		case "INT", "BIGINT", "SMALLINT", "TINYINT", "FLOAT", "DOUBLE", "DECIMAL":
			parts = append(parts, fmt.Sprintf("default(%s)", def))
		case "BOOLEAN":
			// stored as "1"/"0" → convert back to true/false
			if def == "1" {
				parts = append(parts, "default(true)")
			} else {
				parts = append(parts, "default(false)")
			}
		default:
			parts = append(parts, fmt.Sprintf("default('%s')", strings.ReplaceAll(def, "'", "\\'")))
		}
	}

	if col.References != nil {
		refParts := strings.SplitN(*col.References, ".", 2)
		if len(refParts) == 2 {
			parts = append(parts, fmt.Sprintf("references(%s.%s)",
				toCamelCase(refParts[0]), refParts[1]))
		}
	}

	return strings.Join(parts, ".")
}
