package generators

import (
	"fmt"
	"strings"

	"github.com/SleetCo/sleet-orm-cli/internal/loader"
)

// GenerateSQL produces CREATE TABLE IF NOT EXISTS statements for every
// table in the schema. The output is ready to run against a MySQL database.
func GenerateSQL(tables []*loader.TableDef) string {
	var sb strings.Builder

	sb.WriteString("-- AUTO-GENERATED by sleet-cli. DO NOT EDIT MANUALLY.\n")
	sb.WriteString("-- Regenerate with: sleet sql <your-schema.lua>\n")
	sb.WriteString("-- https://github.com/SleetCo/sleet-orm\n\n")

	for _, tbl := range tables {
		sb.WriteString(generateTableSQL(tbl))
		sb.WriteString("\n")
	}

	return sb.String()
}

func generateTableSQL(tbl *loader.TableDef) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS `%s` (\n", tbl.Name))

	var lines []string
	var pkCols []string
	var fkLines []string

	for _, col := range tbl.Columns {
		line := fmt.Sprintf("    `%s` %s", col.Name, sqlTypeDDL(col))

		if col.NotNull {
			line += " NOT NULL"
		} else if !col.HasDefault && !col.DefaultNow {
			line += " NULL"
		}

		if col.AutoIncrement {
			line += " AUTO_INCREMENT"
		}

		switch {
		case col.DefaultNow:
			line += " DEFAULT CURRENT_TIMESTAMP"
		case col.Default != nil:
			line += " DEFAULT " + formatDefaultValue(col)
		}

		if col.Unique && !col.PrimaryKey {
			line += " UNIQUE"
		}

		if col.Comment != "" {
			line += fmt.Sprintf(" COMMENT '%s'", strings.ReplaceAll(col.Comment, "'", "\\'"))
		}

		lines = append(lines, line)

		if col.PrimaryKey {
			pkCols = append(pkCols, "`"+col.Name+"`")
		}

		if col.References != nil {
			parts := strings.SplitN(*col.References, ".", 2)
			if len(parts) == 2 {
				fkLines = append(fkLines, fmt.Sprintf(
					"    FOREIGN KEY (`%s`) REFERENCES `%s` (`%s`)",
					col.Name, parts[0], parts[1],
				))
			}
		}
	}

	if len(pkCols) > 0 {
		lines = append(lines, fmt.Sprintf("    PRIMARY KEY (%s)", strings.Join(pkCols, ", ")))
	}

	lines = append(lines, fkLines...)

	sb.WriteString(strings.Join(lines, ",\n"))
	sb.WriteString("\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n")
	return sb.String()
}

// sqlTypeDDL converts a ColumnDef to a MySQL DDL type string.
func sqlTypeDDL(col *loader.ColumnDef) string {
	t := strings.ToUpper(col.Type)
	switch t {
	case "VARCHAR", "CHAR":
		l := col.Length
		if l <= 0 {
			l = 255
		}
		return fmt.Sprintf("%s(%d)", t, l)
	case "DECIMAL":
		p, s := col.Precision, col.Scale
		if p <= 0 {
			p = 10
		}
		if s <= 0 {
			s = 2
		}
		return fmt.Sprintf("DECIMAL(%d,%d)", p, s)
	case "BOOLEAN":
		return "TINYINT(1)"
	default:
		return t
	}
}

// formatDefaultValue formats a column's default value for use in DDL.
func formatDefaultValue(col *loader.ColumnDef) string {
	if col.Default == nil {
		return "NULL"
	}
	val := *col.Default

	switch strings.ToUpper(col.Type) {
	case "INT", "BIGINT", "SMALLINT", "TINYINT", "FLOAT", "DOUBLE", "DECIMAL", "BOOLEAN":
		return val
	default:
		return fmt.Sprintf("'%s'", strings.ReplaceAll(val, "'", "\\'"))
	}
}
